# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-3
  region: us-east-1

# managednodeGroups will be maintained by AS
managednodeGroups:
  - name: expense-3
    instanceTypes: ["m5.large","c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    #spot: true
    